### ISSUE TITLE
Rotate Layer

### ISSUE THREAD

**Issue by brannondorsey** [kibio/kibio#18]

**Comment by bakercp** [comment]
All of this rotation, scaling, selection, etc stuff would benefit from https://github.com/bakercp/ofxRectangleUtils.

I designed it for doing Illustrator like rectangle manipulations.

**Comment by bakercp** [comment]
It also handles ordering, etc.

**Comment by brannondorsey** [comment]
Big :+1:. Will look into it, thanks!

**Comment by brannondorsey** [comment]
Will it matter that we are more dealing with polyline like quads than right angle rects? Are you suggesting that we use the addon or draw code from it?

**Comment by bakercp** [comment]
from a gui perspective every object and layer can be represented by an AABB / rectangle once it hits the screen (i.e. when you are dragging them around moving layers, etc), so a lot of the basics will apply.  i'm suggesting using it or pulling code from it.  whatever makes the most sense.

**Comment by brannondorsey** [comment]
This is now implemented in develop as of 1ef1ddb758c60c8. Currently you can change transform modes with:
- cmd-t - Translate
- cmd-r - Rotate
- cmd-s - Scale (coming soon).

This is handled internally by the `Project` and the current `TransformType` (enum) value `_transform` determines which mode is active. These keybindings could be more elegant and we should experiment with usability once all transform methods are working.
