### ISSUE TITLE
Cursor Disappear

### ISSUE THREAD

**Issue by brannondorsey** [kibio/kibio#19]
The OSX cursor disappear bug in OF Master is fairly debilitating. @bakercp Is there a simple solution/hack that can be implemented quickly for our purposes (next weekend)? If not I propose that we find a creative commons cursor pack and draw the cursor ourselves. This is a bit hacky but it would reduce ~50% of the complaints received from the feedback at our last workshop and also allow us to convey some varied visual feedback (with a few different cursors like hands, pointer fingers, etc...) for our reduced GUI interface.

**Comment by bakercp** [comment]
Is there a possibility of going back to 0.8.4?  I can't remember ...

**Comment by brannondorsey** [comment]
I bet that we could. Although is 0.8.4 void of this problem? I remember experiencing it with the last project that I worked on with that release.

**Comment by brannondorsey** [comment]
Just rolled back to v0.8.4 (requiring only two adjustments of `ofDrawLine()` to `ofLine` and `ofDrawRectangle` to `ofRect` in ofxQuadWarp), however the mouse hide bug persists. I am going to look into using cursor packs.

**Comment by bakercp** [comment]
Alternatively, we could just build with the latest GLFW and this should be solved.

**Comment by brannondorsey** [comment]
That might be an endeavor that is beyond me in this small amount of time. Is that something that you would be down to tackle?

**Comment by bakercp** [comment]
Definitely.

**Comment by brannondorsey** [comment]
Fantastic! Thanks much. I am going to send you a more detailed email tonight discussing some of the steps and needed preparation for the upcoming workshop.

**Comment by bakercp** [comment]
Alright, lets move back to master.  I'll get a branch updated with GLFW tonight.

**Comment by bakercp** [comment]
OK.  If you use my `develop-apothecary` branch, this should be fixed.

**Comment by brannondorsey** [comment]
What a beautifully permanent mouse. Only now it seems that `ofSetCurrentRenderer()` is no longer supported with the `ofGLProgrammableRenderer::TYPE` parameter. Thoughts on how to fix this?

**Comment by brannondorsey** [comment]
Closing and moving `ofSetCurrentRenderer()` error into a new issue.
