### ISSUE TITLE
Bad Rotate Maths

### ISSUE THREAD

**Issue by brannondorsey** [kibio/kibio#20]
Maybe its just late, but I am running into some gnarly math troubles in trying to get the angle between a mouse and a centroid (by which to rotate a layer). My angles are always exactly backwards and I can't for the life of me figure out what needs to be changed in order to accurately calculate the angle between the two vectors.

```cpp
ofPoint centroid = _layers[_currentLayerIndex]->getCentroid();

float radius = 70;
ofPoint deltaVec = mouse - centroid;
float rad = atan2(deltaVec.x, deltaVec.y) - (PI/2.0);
float x = radius * cos(rad) + centroid.x;
float y = radius * sin(rad) + centroid.y;

ofCircle(centroid, 10);
ofLine(centroid, ofPoint(x, y));
ofNoFill();
ofCircle(centroid, radius);
ofFill();
```

To try the demo live checkout my master branch and:

1. Press cmd-r to go into rotate mode
2. Click a layer to view the visual rotation feedback (that is currently wrong)

**Comment by bakercp** [comment]
Hmm ... can't find the code.

**Comment by brannondorsey** [comment]
[Here is a link](https://github.com/kibio/kibio/blob/1f9c632cfa76dda3658567c4cd20ac555256502c/src/Project.cpp#L98-L110).

**Comment by brannondorsey** [comment]
I'm well on my way to fixing this. More soon.

**Comment by brannondorsey** [comment]
I'm using `ofVec2f::angle()` which seems to only give degrees in 0 to 180, not -180 to 180 or 0 to 360. Values rollover so that it is ambiguous as to wether 90 degrees means clockwise or counterclockwise. I've got [the code](https://github.com/brannondorsey/kibio/blob/d9033992eb630939c7f925ad2a84dcbbda43532f/src/Project.cpp#L724-L729) working to visualize rotations in my `develop` branch, but haven't implemented the actual rotations yet because I haven't figured this out yet.

**Comment by brannondorsey** [comment]
This functionality is now working correctly in develop. I may have found a strange bug in OF master though where `ofPoint::angle()` will not return a negative angle, while `ofVec2f::angle` will. Is `ofPoint` not just a `typedef` for `ofVec2f` (or `ofVec3f`)?

**Comment by bakercp** [comment]
Lot's of current discussion on this topic here https://github.com/openframeworks/openFrameworks/issues/2060
