### ISSUE TITLE
ofSetCurrentRenderer() missing from OF Master

### ISSUE THREAD

**Issue by brannondorsey** [kibio/kibio#21]
`ofSetCurrentRenderer()` is missing from OF master (at least with the method signature that we are using). This is currently prohibiting us from using the programmable renderer in `main.cpp` with:

```cpp
ofSetCurrentRenderer(ofGLProgrammableRenderer::TYPE);
```

**Comment by bakercp** [comment]
See more recent examples:

https://github.com/openframeworks/openFrameworks/blob/master/examples/gl/areaLightExample/src/main.cpp

etc.

**Comment by bakercp** [comment]
That fix it?

**Comment by brannondorsey** [comment]
You bet!
