### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by brannondorsey** [kibio/kibio#24]
![kibio](https://cloud.githubusercontent.com/assets/3193533/6551326/a2cecfae-c604-11e4-846a-e4472b34a108.png)

Clockwise from top:
- Project name
- Mask tool
- Translate tool
- Rotate tool
- Scale tool
- Toggle mode tool
- Info button (displays all key shortcuts)
- New project button
- Open project button
- Save project button

Glyphs from [here](http://www.entypo.com/).

Also, whenever a tool becomes covered by a layer, a pop-up notifies the user that they may hide the interface by pressing "h".

**Comment by brannondorsey** [comment]
@bakercp, what do you think about this? My inclination is to get a simple version of something like this working FAST if at all possible for the workshop. Do you think that the project is stable enough as it is to make this a pressing matter for this weekend?

**Comment by bakercp** [comment]
It looks nice to me.  If you could get something like this working for the weekend that would be super cool.  Regarding stability -- I'm really not sure.  My experiments always found it fairly stable ... but clearly it wasn't ... so ... I'd say we should make sure that the most obvious bugs are squashed (things that make it crash).

**Comment by brannondorsey** [comment]
Alright, great! I'm getting started with this on a [new `interface` branch](https://github.com/brannondorsey/kibio/tree/interface) if you would like to follow its progress.

**Comment by brannondorsey** [comment]
This has been merged into develop and is now ready for testing.

**Comment by brannondorsey** [comment]
Fixed ugly PNGs in a7cf34fc68970ad44be66259080b0e9ec448f9fe. Closing this issue. Individual interface bugs can be opened in their own issues.
