### ISSUE TITLE
Manage Layer Order

### ISSUE THREAD

**Issue by brannondorsey** [kibio/kibio#30]
Layer ordering should be manageable in a manner similar to Adobe Illustrator:

- Layer up: CMD-]
- Layer down: CMD-[
- Bring layer to front: SHIFT-CMD-]
- Bring layer to back: SHIFT-CMD-[

I'm going to try and push this out by tomorrows release as this is a fairly infuriating feature to be without.

**Comment by bakercp** [comment]
This appears to be fixed with 0.2.2.
